export const infoJugadores = [
    { nombre: "Kobe Bryant", 
        equipo: "Los Angeles Lakers", 
        posicion: "Escolta", altura: "1.98m", 
        edad: 41, pPP: 25.0, rPP: 5.2, aPP: 5, 
        porcentajeTiros: 44.7,
        img: "/assets/photos/_110655507_kb.jpg" },
    
        { nombre: "Michael Jordan", 
        equipo: "Chicago Bulls", 
        posicion: "Escolta", altura: "1.98m", 
        edad: 57, pPP: 30.1, rPP: 6.2, aPP: 5.3, 
        porcentajeTiros: 49.7,
        img: "/assets/photos/jordan_michael_1.jpg" },
    
        { nombre: "LeBron James", 
        equipo: "Los Angeles Lakers", 
        posicion: "Alero", altura: "2.06m", 
        edad: 36, pPP: 27.0, rPP: 7.4, aPP: 7.4, 
        porcentajeTiros: 50.4,
        img: "/assets/photos/lebron-james-los-angeles-lakers_8tf0xx4nad6e1t1gpm6fdczyc.png" },
    
        { nombre: "Kareem Abdul-Jabbar", 
        equipo: "Los Angeles Lakers", 
        posicion: "Pívot", altura: "2.18m", 
        edad: 73, pPP: 24.6, rPP: 11.2, aPP: 3.6, 
        porcentajeTiros: 55.9,
        img: "/assets/photos/kareem-abdul-jabbar-zfvtrzdmlck91kbkypla29ass-1584662719315.webp" },

        { nombre: "Magic Johnson",
        equipo: "Los Angeles Lakers",
        posicion: "Base", altura: "2.06m",
        edad: 62, pPP: 19.5, rPP: 7.2, aPP: 11.2,
        porcentajeTiros: 52.0,
        img: "/assets/photos/Magic-Johnson.webp" },

    { nombre: "Stephen Curry", 
        equipo: "Golden State Warriors", 
        posicion: "Base", altura: "1.91m", 
        edad: 35, pPP: 24.3, rPP: 4.5, aPP: 6.5, 
        porcentajeTiros: 43.7,
        img: "/assets/photos/stephen-curry.jpg" },
    
    { nombre: "Kevin Durant", 
        equipo: "Phoenix Suns", 
        posicion: "Alero", altura: "2.08m", 
        edad: 34, pPP: 26.0, rPP: 7.1, aPP: 5.0, 
        porcentajeTiros: 49.2,
        img: "/assets/photos/kevin-durant.jpg" },
    
    { nombre: "Giannis Antetokounmpo", 
        equipo: "Milwaukee Bucks", 
        posicion: "Ala-Pívot", altura: "2.11m", 
        edad: 28, pPP: 29.9, rPP: 11.8, aPP: 5.6, 
        porcentajeTiros: 55.1,
        img: "/assets/photos/giannis.jpg" },
    
    { nombre: "Nikola Jokic", 
        equipo: "Denver Nuggets", 
        posicion: "Pívot", altura: "2.11m", 
        edad: 28, pPP: 26.4, rPP: 10.8, aPP: 7.2, 
        porcentajeTiros: 58.3,
        img: "/assets/photos/nikola-jokic.jpg" },
    
    { nombre: "Kawhi Leonard", 
        equipo: "Los Angeles Clippers", 
        posicion: "Alero", altura: "2.01m", 
        edad: 31, pPP: 25.5, rPP: 6.6, aPP: 4.9, 
        porcentajeTiros: 49.1,
        img: "/assets/photos/kawhi-leonard.jpg" }

];